---
user: vagrant

local:
  assets_dir: "~/.kube/vagrant"


masters: &masters
  - 192.168.43.111
  - 192.168.43.112
workers: &workers
  - 192.168.43.113
  - 192.168.43.114

roledefs:
  bootstrap:
  - 192.168.43.111
  etcd: *masters
  master: *masters
  worker: *workers

etcd:
  hosts:
    "192.168.43.111": node01.local
    "192.168.43.112": node02.local

kubernetes:
  version: v1.11.1
  public_service_ip: 192.168.43.110
