---
temp_dir: "/tmp/kube_temp"

local:
  shell: "/bin/bash"
  kubeconfig: "~/.kube/config"
  kubectl: "kubectl"
local_shell: "/bin/bash"
local_kubeconfig: "~/.kube/config"
local_kubectl: "kubectl"

docker:
  path: "/usr/bin/docker"

haproxy:
  keepalived_vrid: "1"
  keepalived_auth_password: "himitsu"
  keepalived_use_unicast: "true"

kubernetes:
  version: v1.9.6
  hyperkube_image_repo: gcr.io/google_containers/hyperkube
  cluster_cidr: 10.244.0.0/16
  node_cidr_mask_size: 24
  service_ip_range: 10.254.0.0/24
  cluster_dns_ip: 10.254.0.10
  additional_hostnames: []
  private_service_ip: 10.254.0.1
  additional_service_ips: []
  network_plugin: "cni"
  cni_plugin: "flannel"
  volume_plugin_dir: "/var/lib/kubelet/volumeplugins"
  port: 6443
  internal_port: 6444
  admission_control: "NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,ResourceQuota"
  storage_backend: etcd3
  certs_dir: "/etc/kubernetes/pki"
  log_level: 2
  cloud_provider: ""
  cloud_config: ""
  upstream_nameservers: '[\"8.8.8.8\", \"8.8.4.4\"]'
  addons: ["kube-proxy", "kube-dns"]

etcd:
  selfhosted: "false"
  version: "v3.1.8"
  image_repo: "quay.io/coreos/etcd"
  certs_dir: "/etc/etcd/pki"
  cluster_ip: 10.254.0.20
  bootstrap_cluster_ip: 10.254.0.30
  heartbeat_interval:: 100

flannel:
  version: "v0.10.0-amd64"
  image_repo: quay.io/coreos/flannel
  backend_type: vxlan
  cni_version: "v0.3.0"
  cni_image_repo: "quay.io/coreos/flannel-cni"
